export const core = {
  PI: Math.PI,
  E: Math.E,
  sin: Math.sin,
  cos: Math.cos,
  tan: Math.tan,
  asin: Math.asin,
  acos: Math.acos,
  atan: Math.atan,
  round: Math.round,
  max: Math.max,
  min: Math.min,
  log: Math.log,
  log10: Math.log10,
  log2: Math.log2,
  sqrt: Math.sqrt,
  pow: Math.pow,
  random: Math.random,
  ceil: Math.ceil,
  floor: Math.floor,
  '+': (a: number, b: number) => a + b,
  '-': (a: number, b: number) => a - b,
  '*': (a: number, b: number) => a * b,
  '/': (a: number, b: number) => a / b,
  '=': (a: number, b: number) => a === b,
  '>': (a: number, b: number) => a > b,
  '<': (a: number, b: number) => a < b,
  '>=': (a: number, b: number) => a >= b,
  '<=': (a: number, b: number) => a <= b,
  eq: (a: string, b: string) => a === b,
  concat: (...args: string[]) => args.join(''),
  'to-fixed': (n: number, decimalPlaces: number) => n.toFixed(decimalPlaces),
  print: (message: string) => {
    console.log(message);
    return null;
  },
};
