const {
  PI,
  E,
  sin,
  cos,
  tan,
  asin,
  acos,
  atan,
  round,
  max,
  min,
  log,
  log10,
  log2,
  sqrt,
  pow,
  random,
  ceil,
  floor,
} = Math;

export const core = {
  PI,
  E,
  sin,
  cos,
  tan,
  asin,
  acos,
  atan,
  round,
  max,
  min,
  log,
  log10,
  log2,
  sqrt,
  pow,
  random,
  ceil,
  floor,
  '+': (a: number, b: number) => a + b,
  '-': (a: number, b: number) => a - b,
  '*': (a: number, b: number) => a * b,
  '/': (a: number, b: number) => a / b,
  '=': (a: number, b: number) => a === b,
  '>': (a: number, b: number) => a > b,
  '<': (a: number, b: number) => a < b,
  '>=': (a: number, b: number) => a >= b,
  '<=': (a: number, b: number) => a <= b,
  eq: (a: string, b: string) => a === b,
  concat: (...args: string[]) => args.join(''),
  'to-fixed': (n: number, decimalPlaces: number) => n.toFixed(decimalPlaces),
  print: (message: string) => {
    console.log(message);
    return null;
  },
};
